### PR TITLE
HTML / CSS Overhaul

### PR DESCRIPTION
**Pull request by jackbrewer**
**Refactor of Stylus / Jade**
Front-End and Admin structure / styling has been rewritten, with changes including:
- An updated, more minimal admin theme
- Basic work on front-end theme
- Removed Stylus / Jade bloat
- Reorganised Stylus / Jade components into separate includes
- Increased consistency between front-end and admin file structures
- Rewritten Jade for major components: layouts, header, footer, navigation etc.
- Rewritten head element to include more useful information
- Refactored form mixins and added new form elements: full-width textareas and (currently static) D.O.B. fields
- Increased HTML semantics in forms and other components
- Removed custom CSS3 mixins from admin, in favour of nib
- Removed incomplete grid system component

This update may leave some non-core components with styling inconsistencies.

### CODE REVIEW

**Comment by evlun** [comment]
Holy pull request, batman!

**Comment by bengourley** [comment]
Looks lush. @serby if the form mixins have changed, we will need to have a look at the form post processors on the default bundles to make sure fields get coerced ok.

**Comment by ghost** [comment]
Nice changes.

**Comment by tomgco** [comment]
Woah, nice work @jackbrewer!

**Comment by serby** [comment]
Looks great. Does it close off either of these: #70 #71

**Comment by jackbrewer** [comment]
It adds a full width textarea which should close #71 - see the article create/edit page for 2 examples

Regarding #70, you can now pass the mixin a 'rows' property to set bespoke heights on textareas. This is more flexible than a set of class names but it's arguable whether that level of control is needed. Again, see the article create/edit page for 2 examples: 'Article Content' has a bespoke row attribute, 'Article Summary' has the default.

@bengourley The form mixins haven't changed in terms of functionality - they've just been separated for readability and have had semantic Jade changes.

**Comment by jackbrewer** [comment]
Also, just so everyone knows - the purpose of this work was mainly to improve the basic HTML/CSS framework.

There's still a lot to do on the front-end so if you spot anything odd, unstlyed, or have any ideas, please say!

**Pull request merged**
