### PR TITLE
Add user confirm dialog to all 'delete' anchors.

### PR DESCRIPTION
**Pull request by bengourley**
Prevent accidental delete by showing a confirm dialog on links that have a class of delete.

### CODE REVIEW

**Comment by serby** [comment]
Delete isn't confirming anymore in ctrl

**Comment by jackbrewer** [comment]
I think it would be wise to have a non-JS fallback for this if possible - it's quite a major action.

**Comment by serby** [comment]
Agreed. As soon as JavaScript breaks on the page the safeguard is gone.

Maybe make the delete action only work when confirm embellishment is added.

**Comment by bengourley** [comment]
+1

**Pull request merged**
