### PR TITLE
Fixes for issues #31 and #32

### PR DESCRIPTION
**Pull request by evlun**
https://github.com/serby/control/issues/31
https://github.com/serby/control/issues/32

Regarding the ACL issue: we could set a short-lived session variable/querystring variable/cookie pointing to the URL the user was trying to access, and then redirect to it again on a successful login. I'm not sure how to handle failed POST requests, though.

### CODE REVIEW

**Comment by evlun** [comment]
Role grants look like this in listings/views now:



This will apply to all generic fields of type `groupedMultiselect`.

**Comment by serby** [comment]
I'm happy with what you've done on Roles but it, but I'll wait until I can pull both.

**Comment by serby** [comment]
If you have a commit to remove the hard '/admin/login' push that and we can tackle the JSON service issue another time.

**Comment by evlun** [comment]
@serby I have removed the hard `/admin/login` redirect now.

**Comment by serby** [comment]
I was hoping that rather than passing in to each middleware. You could pass it in on creation of the adminAccessControlList in the admin/bundle.js

**Comment by evlun** [comment]
Yes I see. I was hesitant to do this at first as the access control function gets exported via the service locator, but I can't think of any actual impact this would have.

**Comment by serby** [comment]
It will be fine because you create one for each type of resource you
want to control access for. In this case the admin bundles. As long as
you can still override it at the middleware level.

Sent from a telephone

On 26 Jul 2012, at 18:04, Erik Lundin
reply@reply.github.com
wrote:

**Pull request merged**
